apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-ui
  template:
    metadata:
      labels:
        app: my-ui
    spec:
      containers:
        - name: my-ui
          image: ghcr.io/Benjakunee17/my-ui:latest
          ports:
            - containerPort: 80
  strategy:
    canary:
      stableService: my-ui-stable
      canaryService: my-ui-canary
      steps:
        - setWeight: 20
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }