apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-ui
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-ui
  template:
    metadata:
      labels:
        app: my-ui
    spec:
      containers:
        - name: my-ui
          image: my-ui:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
  strategy:
    canary:
      stableService: my-ui-stable
      canaryService: my-ui-canary
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s