apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace ของ production
namespace: my-ui-prod

resources:
  - ../../base

# ใส่ label ให้ resource ทั้งหมดใน prod
labels:
  - pairs:
      env: prod

# ตอน promote แค่แก้ newTag บรรทัดเดียว
images:
  - name: ghcr.io/benjakunee17/my-ui
    newName: ghcr.io/benjakunee17/my-ui
    newTag: 90df3e4  # 👈 เปลี่ยนตรงนี้ตอน promote

patches:
  # -----------------------------
  # เปลี่ยน host เป็น domain prod จริง
  # -----------------------------
  - target:
      kind: Ingress
      name: my-ui
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: my-ui.company.com

  # -----------------------------
  # เพิ่ม replicas ให้ prod
  # -----------------------------
  - target:
      kind: Rollout
      name: my-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

  # -----------------------------
  # ทำ Canary แบบ Production
  # - slow
  # - manual promote
  # - analysis metric
  # -----------------------------
  - target:
      kind: Rollout
      name: my-ui
    patch: |-
      - op: replace
        path: /spec/strategy/canary/steps
        value:
          - setWeight: 5
          - pause: {}     # manual approve
          - analysis:
              templates:
                - templateName: success-rate

          - setWeight: 20
          - pause: {}     # manual approve
          - analysis:
              templates:
                - templateName: success-rate

          - setWeight: 50
          - pause: {}     # manual approve
          - analysis:
              templates:
                - templateName: success-rate

          - setWeight: 100

  # -----------------------------
  # เปิด NGINX traffic routing ให้ Rollouts
  # - ให้ setWeight มีผลกับ ingress (stableIngress)
  # - และถ้า analysis fail → abort แล้ว traffic จะคงที่ stable
  # -----------------------------
  - target:
      kind: Rollout
      name: my-ui
    patch: |-
      - op: add
        path: /spec/strategy/canary/trafficRouting
        value:
          nginx:
            stableIngress: my-ui

      - op: add
        path: /spec/strategy/canary/abortScaleDownDelaySeconds
        value: 0

  # -----------------------------
  # บังคับ pod template label ให้เป็น prod
  # (base มี env: dev อยู่แล้ว ต้องใช้ replace)
  # -----------------------------
  - target:
      kind: Rollout
      name: my-ui
    patch: |-
      - op: replace
        path: /spec/template/metadata/labels/env
        value: prod
