#ให้ Argo CD deploy ELK จาก repo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Benjakunee17/argo-canary.git
    targetRevision: main
    path: gitops/apps/my-ui/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true